---
- name: Squid proxy setup
  vars_prompt:
    - name: proxy_username
      prompt: "Proxy username"
      private: no
    - name: proxy_password
      prompt: "Proxy password"
      confirm: yes
      private: yes
    - name: proxy_port
      prompt: "Proxy port"
      default: 3128
  pre_tasks:
    - name: Install prerequisite packages
      apt:
        name:
          - python
          - python-pip
          - python-virtualenv
          - python-passlib
        state: latest
        update_cache: yes
        cache_valid_time: 86400
  roles:
    - squid
  become: yes
  hosts: kogane-vpn
...
